Update create-tag.yml

diff --git a/.github/workflows/create-tag.yml b/.github/workflows/create-tag.yml
--- a/.github/workflows/create-tag.yml
+++ b/.github/workflows/create-tag.yml
@@ -12,9 +12,8 @@ on:
       repo: 
         description: "The repo that hosts the service to be deployed"
         value: ${{ jobs.create_tag.outputs.repo }}
-      repo_short: 
-        description: "The repo's short name that hosts the service to be deployed"
-        value: ${{ jobs.create_tag.outputs.repo_short }}
+      target:
+        description: "On which environment will the tag be used"
 
 jobs:
   create_tag:
@@ -24,7 +23,7 @@ jobs:
     outputs:
       tag: ${{ steps.create-tag.outputs.tag }}
       repo: ${{ steps.create-tag.outputs.repo }}
-      repo_short: ${{ steps.create-tag.outputs.repo_short }}
+      target: ${{ steps.create-tag.outputs.target }}
     
     steps:
       - id: create-tag
@@ -32,7 +31,10 @@ jobs:
           if [[ ${GITHUB_REF_TYPE} == 'tag' ]]; then
             
             # RC OR PRODUCTION BUILD MODE
+            
             GIT_TAG=$(echo ${GITHUB_REF_NAME})
+            TARGET="preprod"
+            
           else
             
             # DEVELOP / QA BUILD MODE
@@ -40,18 +42,21 @@ jobs:
             
             GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | awk -F'/' '{ print $NF}')
             GIT_TAG=$(echo ${GITHUB_REF#refs/heads/} | awk -F'/' '{ print $NF}')
+            TARGET="develop"
+            
             # !!! SECURITY MEASURE: WE DON'T TRIGGER A DEPLOY IF PUSHING ON THE MAIN BRANCH
-            # !!! CREATE A RELEASE INSTEAD
-            # if [[ $GIT_BRANCH == 'master' || $GIT_BRANCH == 'main' ]]; then
-            #   echo "Workflow run on master/main branch, aborting."
-            #   exit 1
-            # fi
+            if [[ $GIT_BRANCH == 'master' || $GIT_BRANCH == 'main' ]]; then
+              echo "Workflow run on master/main branch, aborting."
+              exit 1
+            fi
           fi
+          
           REPO=$(echo ${GITHUB_REPOSITORY} | awk -F'/' '{ print $NF}')
-          REPO_SHORT=$(echo ${REPO} | awk -F'service-' '{ print $NF}')
+          
           echo "GIT_TAG: ${GIT_TAG}"
           echo "REPO: ${REPO}"
-          echo "REPO_SHORT: ${REPO_SHORT}"
+          echo "TARGET: ${TARGET}"
+          
           echo "tag=$GIT_TAG" >> $GITHUB_OUTPUT
           echo "repo=$REPO" >> $GITHUB_OUTPUT
-          echo "repo_short=$REPO_SHORT" >> $GITHUB_OUTPUT
+          echo "target=$TARGET" >> $GITHUB_OUTPUT
